apiVersion: v1
kind: Service
metadata:
  name: courseservice-service
  namespace: courseservice-ns
spec:
  type: NodePort
  selector:
    app: courseservice
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30081
