name: Build & Deploy to Local Kubernetes

on:
  push:
    branches: ["main"]

env:
  APP_NAME: courseservice
  APP_NAMESPACE: courseservice-ns
  IMAGE_NAME: courseservice-image
  IMAGE_TAG: latest

jobs:
  build-and-deploy:
    runs-on: self-hosted   # runs on your machine

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} -f Dockerfile .

      - name: Set KUBECONFIG
        run: |
          echo "KUBECONFIG=C:\\Users\\user\\.kube\\config" >> $env:GITHUB_ENV

      - name: Deploy to Kubernetes
        shell: pwsh
        run: |
          kubectl apply -f namespace.yaml --validate=false
          kubectl apply -f deployment.yaml --validate=false
          kubectl apply -f service.yaml --validate=false
